---
version: '3.8'
services:
  mydb:
    image: jenkins/jenkins
    ports:
      - 1001:8080
    networks:
      - abc
  qaserver:
    image: tomcat
    ports:
      - 1002:8080
    networks:
      - xyz
  prodserver:
    image: tomcat
    ports:
      - 1003:8080
    networks:
      - xyz
networks:
  abc: {}
  xyz: {}
