---
version: '3.8'
services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: viky11
  volumes:
    mydb: /var/lib/mysql
  wordpress:
    image: wordpress
    ports:
      - 1111:80
  volumes:
    wordpress: /var/www/html
volumes:
  mydb:
    wordpress:
