---
version: '3.8'
services:
  mydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
  adminer:
    image: adminer
    ports:
      - 1100:8080
networks:
  default:
    external:
      name: viky1
